# Site settings
title: Axel Gueudin
email: axel.gueudin@gmail.com
baseurl: ""
url: "https://axelgueudin.fr"
description: "Axel Gueudin, freelance graphic and UX/UI designer based in Rouen, ready to handle your communication needs: logo design, visual identity, print, and UX/UI web design."
keywords: "Graphic Design Portfolio,UI/UX Design Showcase,Freelance Designer Portfolio,Axel Gueudin Portfolio,Graphic Designer Rouen,UI Designer France,UX/UI Design Projects,Visual Identity Design,Logo Design Showcase, Print Design Portfolio,Web Design Portfolio,Branding and Identity,Creative Design Work,Digital Design,Portfolio Website,Art Direction Projects,User Interface Design,User Experience Design,Creative Design Portfolio,Illustration Projects,Typography Design,UI/UX Design Case Studies,Visual Design Projects,Interactive Design,Mobile App Design, Digital Artwork Portfolio,Brand Identity Design"
skills: "Art Director - Graphic Design - User Interface Designer - User Experience Designer"
meta_author: GUEUDIN Axel

timezone: UTC

# Footer settings
footer:
  copyright: ©
  name: Axel GUEUDIN
  location: Rouen, FR
  credits: All Rights Reserved

# Social networks usernames
social:
  - title: instagram
    url: https://instagram.com/axelgueudin
  - title: linkedin
    url: https://linkedin.com/in/axelgueudin
  - title: dribbble
    url: https://dribbble.com/lXlON
  - title: artstation
    url: https://artstation.com/axelgueudin
  - title: behance
    url: https://behance.com/axelgueudin

# Build settings
markdown: kramdown
permalink: pretty
plugins: [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag, jekyll-relative-links]


#for projects
collections:
  projects:
    output: true